sonar.projectKey=fati2809_Maposting-Backend-Final
sonar.organization=fati2809
sonar.projectName=Maposting-Backend-Final
sonar.sources=app
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11
